# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb
    - db/**/*
    - docs/**/*
    - config/**/*
    - bin/**/*
    - script/**/*

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 99

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
